version: "2.0"
services:
  geth-node1:
     hostname: geth-node1
     environment:
       - address=0x3590aca93338b0721966a8d0c96ebf2c4c87c544 #derived from the private key which is passed in the args
       - bootnodeId=76a8171707eca17647a47ca99ffd348927dfa60102792ea349a25d5192e61855be83b786e376276a306afcceea4ffd1c9c77e4370b417efc39f328a0d068004c #derived from the nodekeyhex of the bootnode
       - bootnodeIp=172.25.0.101
     build:
       context: ./geth-node1
       args:
         privatekey: bc5b578e0dcb2dbf98dd6e5fe62cb5a28b84a55e15fc112d4ca88e1f62bd7c35
         password: word
     container_name: geth-node1
     ports:
       - 8545:8545
     volumes:
      - eth-data-1:/root/.ethash
     networks:
       chainnet:
         ipv4_address: 172.25.0.110


  geth-explorer:
    hostname: geth-explorer
    depends_on:
      - geth-node1
    ports:
      - 8787:8080
    build:
      context: ./geth-explorer
    container_name: geth-explorer
    networks:
      chainnet:
        ipv4_address: 172.25.0.111

networks:
  chainnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24

volumes:
  eth-data-1:

